name: Main

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '4.0'
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - name: Set up Ruby
      uses: ruby/setup-ruby@dffb23f65a78bba8db45d387d5ea1bbd6be3ef18 # v1.293.0
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake spec

  build:
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - uses: ruby/setup-ruby@dffb23f65a78bba8db45d387d5ea1bbd6be3ef18 # v1.293.0
      with:
        ruby-version: ruby
    - uses: anchore/sbom-action@57aae528053a48a3f6235f2d9461b05fbcb7366d # v0.23.1
      with:
        output-file: /tmp/sbom.json
        upload-artifact: false
        upload-release-assets: false
    - uses: release-gems/action/build@master # TODO: replace "master" with HASH
      with:
        sbom: /tmp/sbom.json

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    environment: rubygems.org
    runs-on: ubuntu-slim
    permissions:
      contents: write
      id-token: write
    steps:
    - uses: release-gems/action@master # TODO: replace "master" with HASH
